# Generated by Django 4.0.5 on 2022-06-12 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Categoria')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Juguete',
            fields=[
                ('marca', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Marca')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manada.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('marca', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Marca')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('tamanno', models.CharField(max_length=4, verbose_name='Tamaño')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manada.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Accesorios',
            fields=[
                ('marca', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Marca')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('tamanno', models.CharField(max_length=4, verbose_name='Tamaño')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manada.categoria')),
            ],
        ),
    ]
