# Generated by Django 4.0.5 on 2022-06-28 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manada', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=13, primary_key=True, serialize=False, verbose_name='Rut')),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre')),
                ('mail', models.CharField(max_length=40, verbose_name='Gmail')),
                ('telefono', models.CharField(max_length=10, verbose_name='Telefono')),
                ('direccion', models.CharField(max_length=40, verbose_name='Direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUser', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id usuario')),
                ('nombreUser', models.CharField(max_length=50, verbose_name='Nombre usuario')),
            ],
        ),
        migrations.RemoveField(
            model_name='juguete',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Accesorios',
        ),
        migrations.DeleteModel(
            name='Juguete',
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manada.usuario'),
        ),
    ]
