# Generated by Django 4.0.5 on 2022-06-29 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manada', '0002_cliente_usuario_remove_juguete_categoria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='mail',
            new_name='gmail',
        ),
    ]
