# Generated by Django 4.0.5 on 2022-07-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manada', '0003_rename_mail_cliente_gmail'),
    ]

    operations = [
        migrations.AddField(
            model_name='comida',
            name='imagen',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
